project:
  type: website

website:
  title: "Welcome to my blog!"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/mandil-karki-nlp/
      - icon: github
        href: https://github.com/MandilKarki
format:
  html:
    theme: lux
    css: styles.css
